### ISSUE TITLE
Is is possible to download installer somewhere?

### ISSUE THREAD

**Issue by Mangatt** [codehangar/reqlpro#11]
reqlpro.com is not working anymore.

**Comment by grailian** [comment]
Hey Mangatt, we haven't been supporting reqlpro for quite a while now (ever since the rethinkdb org shut down a few years ago, and we had moved all of our services to Postgres), but you can find installers for the last version we did build here in the github releases:

https://github.com/codehangar/reqlpro/releases

**Comment by Mangatt** [comment]
@grailian Thank you!

We did the same, but we still have one project running RethinkDB and ReqlPro is still best way to manage this database.
